name: fashionwear_ecommerce
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/ 
  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/GemunuLibre-Bold.ttf
    - family: Semi-Bold
      fonts:
        - asset: assets/fonts/GemunuLibre-SemiBold.ttf
